---
- hosts: all
  become: true
  tasks:
    - name: Update all servers
      shell:
        cmd: "sudo docker service update --force --image {{ image_name }}:{{ image_tag }} {{ service_name }}"
    - name: Update ${{ service_name }}={{ image_tag }}
      ansible.builtin.lineinfile:
        path: ~/.bashrc
        regexp: 'export {{ service_name }}='
        line: 'export {{ service_name }}={{ image_tag }}'

    - name: Clean up docker system
      shell:
        cmd: sudo docker system prune -fa
