---
- hosts: all
  become: true
  tasks:
    - name: Update all servers
      shell:
        cmd: "sudo docker service update --force --image {{ image_name }}:{{ image_tag }} {{ service_name }}"
    - name: Replace {{ service_name }}={{ image_tag }}
      ansible.builtin.lineinfile:
        path: "/etc/environment"
        regexp: '{{ service_name }}='
        line: '{{ service_name }}={{ image_tag }}'
    - name: Update source for {{ service_name }}={{ image_tag }}
      shell:
        cmd: source ~/.bashrc
      args:
        executable: /bin/bash
    - name: Clean up docker system
      shell:
        cmd: sudo docker system prune -fa
