---
- hosts: all
  become: true
  tasks:
    - name: Copy env
      shell:
        cmd: |
          env_contents="{{ env }}";
          echo "$env_contents"
          echo "$env_contents" > /var/www/deploy/{{ env_file_name }}
    - name: Update all servers
      shell:
        cmd: "bash /var/www/deploy/run_prd.sh"
