---
- hosts: all
  become: true
  tasks:
    - name: Copy env
      shell:
        cmd: |
          env_contents="{{ env }}";
          echo $env_contents > /var/www/deploy/{{ env_file_name }}
    - name: Update all servers
      shell:
        cmd: "sudo docker service update --force --image {{ image_name }}:{{ image_tag }} {{ service_name }}"
