---
- hosts: all
  become: true

  tasks:
    - name: Copy env
      shell:
        cmd: |
          env_contents="{{ env }}";
          echo "$env_contents" > /var/www/deploy/{{ env_file_name }}
    - name: Update all servers
      args:
        executable: /bin/bash
      shell:
        chdir: /var/www/deploy
        cmd: source /root/.bashrc && bash run_prd.sh
