# .github/workflows/poweron.yml
name: Power On Droplet

on:
  workflow_dispatch:
    inputs:
      domain:
        options:
          - 'easy-web.gr'
        description: fds
  workflow_call:
    inputs:
      domain:
        description: "Environment to deploy to"
        required: true
        type: string

jobs:
  poweron:
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        run: |
          sudo snap install doctl --classic


      - name: Power on Droplet and Wait
        run: |
          echo "Powering on Droplet ID ${{ secrets.DROPLET_ID }}..."
          doctl compute droplet-action power-on ${{ secrets.DROPLET_ID }} --access-token ${{ secrets.DO_TOKEN }}

          echo "Waiting for droplet to become active..."
          while true; do
            STATUS=$(doctl compute droplet get ${{ secrets.DROPLET_ID }} --format Status --no-header --access-token ${{ secrets.DO_TOKEN }})
            echo "Current status: $STATUS"
            if [ "$STATUS" == "active" ]; then
              echo "Droplet is active."
              break
            fi
            sleep 5
          done

          echo "Waiting for domain ${{ inputs.domain }} to respond..."
          while true; do
            if ping -c 1 "${{ inputs.domain }}" &>/dev/null; then
              echo "${{ inputs.domain }} is reachable."
              break
            else
              echo "Waiting for ${{ inputs.domain }} to respond..."
              sleep 5
            fi
          done
          echo "Operation complete."
