# .github/workflows/poweron.yml
name: Power On Droplet

on:
  workflow_call:
    inputs:
      domain:
        description: "Environment to deploy to"
        required: true
        type: string
    secrets:
      droplet_id:
        required: true
      do_token:
        required: true

jobs:
  poweron:
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        run: |
          sudo snap install doctl --classic


      - name: Power on Droplet and Wait
        run: |
          echo "Powering on Droplet ID ${{ secrets.droplet_id }}..."
          doctl compute droplet-action power-on ${{ secrets.droplet_id }} --access-token ${{ secrets.do_token }}

          echo "Waiting for droplet to become active..."
          while true; do
            STATUS=$(doctl compute droplet get ${{ secrets.droplet_id }} --format Status --no-header --access-token ${{ secrets.do_token }})
            echo "Current status: $STATUS"
            if [ "$STATUS" == "active" ]; then
              echo "Droplet is active."
              break
            fi
            sleep 5
          done
          
          
          sleep 10;
          exit 0;
