name: Docker Build

on:
  workflow_call:
    inputs:
      image_name:
        description: 'Name of the Docker image'
        required: true
        type: string
      env:
        description: 'Environment variables'
        required: false
        type: string
        default: ""
      image_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'
        type: string
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true

jobs:
  build_deploy:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
           docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        run: |
          env_contents="${{inputs.env}}";
          echo "$env_contents" > ./.env;
          TAG=$(echo ${{ inputs.image_tag }} | sed 's/[:,\/]/-/g')
          docker build -t ${{ inputs.image_name }}:${TAG} .
          docker push ${{ inputs.image_name }}:${TAG}