name: Deploy to environment
on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: string
    secrets:
      zone_id:
        required: true
      api_key:
        required: true
      email:
        required: true

jobs:
  prepare:
    name: Purge Cloudflare cache
    runs-on: ubuntu-latest
    steps:
      - name: Call the purge cache api
        run: |
          curl --request POST \
            --url https://api.cloudflare.com/client/v4/zones/${{ secrets.zone_id }}/purge_cache \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Bearer ${{ secrets.api_key }}' \
            --data '{
               "purge_everything": true
            }'